configName: sam_e54_xpro
folderName: ''
format_version: v1.0
frameworkPath: ../../../..
processor: ATSAME54P20A
projectName: ''
settings:
  PackageFilter: csp_apps_sam_d5x_e5x;dev_packs;csp;quick_docs;harmony-services
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  CMSISPath: ./dev_packs/arm/CMSIS/5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: ./dev_packs/Microchip/SAME54_DFP/3.7.122/atdf/ATSAME54P20A.atdf
